### ISSUE TITLE
Application does not load on linux

### ISSUE THREAD

**Issue by gentlegiantJGC** [Amulet-Team/Amulet-Editor#42]
When running the application on linux (from the terminal) the command line output is shown but there are now windows shown.

**Comment by Max-RM** [comment]
it looks like this:
![Screenshot_2023-03-16-10-58-22-605_com realvnc viewer android](https://user-images.githubusercontent.com/81485476/225528888-ced49ff1-7fc8-446a-8edd-372abcd22235.jpg)

**Comment by gentlegiantJGC** [comment]
I have since gotten this running on Ubuntu.
I don't know what is stopping this working on your OS

**Comment by Max-RM** [comment]
> I have since gotten this running on Ubuntu. I don't know what is stopping this working on your OS

Maybe I should give access to my device via AnyDesk?  Then you can catch reason of error.
