### ISSUE TITLE
Errror on Linux ARM64

### ISSUE THREAD

**Issue by Max-RM** [Amulet-Team/Amulet-Editor#55]
Platform - Debian bullseye ARM64.

Amulet-Editor requires Pyside 6. there is no compiled Pyside 6 for ARM64, which is why need to perform these actions first: [https://gitlab.com/-/snippets/2432339](https://gitlab.com/-/snippets/2432339) 
[https://github.com/Amulet-Team/Amulet-Core/issues/233#issuecomment-1416740274](https://github.com/Amulet-Team/Amulet-Core/issues/233#issuecomment-1416740274) 

After this qt example start works:
[https://github.com/Amulet-Team/Amulet-Map-Editor/issues/127#issuecomment-907820305](https://github.com/Amulet-Team/Amulet-Map-Editor/issues/127#issuecomment-907820305) 
[https://youtu.be/438FJJjgkT8](https://youtu.be/438FJJjgkT8) 

after that, the Amulet-Editor worked for a while:
![Screenshot_2023-02-06-14-13-40-310_com realvnc viewer android](https://github.com/Amulet-Team/Amulet-Editor/assets/81485476/1547fb14-0b4c-44b5-a5e7-b550ae06e60d)

then it stopped working correctly:
[https://github.com/Amulet-Team/Amulet-Editor/issues/42](https://github.com/Amulet-Team/Amulet-Editor/issues/42) 

now, after some time, the Amulet-Editor at least shows an error in the terminal, and not just does not show the ui without error log:
![Screenshot_2023-08-04-10-15-38-028_com realvnc viewer android](https://github.com/Amulet-Team/Amulet-Editor/assets/81485476/c12df8ed-0571-462a-880a-7f34365c9887)
`QSocketNotifier: Can only be used with threads started with QThread`

`Traceback (most recent call last):??  File "/usr/local/lib/python3.10/site-packages/amulet_editor/__main__.py", line 54, in main??    app_main()??  File "/usr/local/lib/python3.10/site-packages/amulet_editor/application/_app.py", line 104, in app_main??    rpc.init_rpc(is_broker)??  File "/usr/local/lib/python3.10/site-packages/amulet_editor/data/_rpc.py", line 339, in init_rpc??    raise Exception(msg)??Exception: QLocalServer::listen: Address in use`

windows with errors appear again and again and there are a lot of them.

**Comment by gentlegiantJGC** [comment]
I think I fixed this issue

**Comment by Max-RM** [comment]
> I think I fixed this issue
now, again, no errors appear in the console or anywhere else, and the program window does not appear.

**Comment by Max-RM** [comment]
After some [fixes in code](https://discord.com/channels/324647192583340043/858645423928508416/1149017683380162570) program window finally appear, and [3d view also works!](https://youtu.be/DKEE9D-lris?si=-hmILt77f_OzEBOu)
